### PR TITLE
some major changes added issue & issue comment API implementations

### PR DESCRIPTION
**Pull request by drdamour**
...for issues & issue comments

renamed because this isn't just for csharp (although it's written in it)
also wanted to limit the - in the namespace as this is very rarely seen
in .net
added VSTests alongside Nunit tests because the express products can't
use the Nunit test adapter extension (which sucks)
FYI A test project can have an App.config, which i think is a bit nicer
than the .dll.config you had people using

### CODE REVIEW

**Comment by sgrassie** [comment]
Hi, thanks for the pull request. A few thoughts:
- Changing the namespace is something I've been meaning to do, but just haven't gotten round to yet. I'd want to change it so that it's fairly clear it's not a github.com product/project. E.g. changing to something like TemporalCohesion.GithubAPI is my choice.
- Mixing unit test frameworks like this is not something I want to do. Coming up with a better solution for this along the lines of http://geekswithblogs.net/TheCodeMonkey/archive/2012/09/15/how-to-write-your-unit-test-to-switch-between-nunit.aspx would be preferable. 
- Already using an App.config, I'm just forcing people to build it themselves.

I'll go through your commits in detail later on.

**Comment by drdamour** [comment]
Cool, glad you agree on namespace, i can make that change in this pull, but i suggest
TemporalCohesion.GitHubAPI
over
TemporalCohesion.GithubAPI
agree?

That's a nice solution to the NUnit problem, let me try that tonight, wish i had known about that earlier!

the readme tells people to use  dll.config, & it's pretty common to check in an app.config.  I'll add change to the readme for the new instructions.

**Comment by drdamour** [comment]
OK i went with that NUnit fix...worked pretty well. Few issues:
1. VS Ignore attribute can't take a reason, i just removed the reason in the 1 place
2. FactAttribute & ObservationAttribute should conditionally inherit from VS TestMethodAttribute, but it's sealed, i just redefined them to the appropriate attribute in each test file as i could
3. You have TestFixture on a deep base class, presumably because TestFixture is inherited on derived types..but the VSTest equivalent is non-inheritable.  Thus I had to add this annotation to every test class.

I could use some guidance on how we should test stuff that actually changes things.  Seems like we should create a test repo on demand, agree?

**Comment by sgrassie** [comment]
I've pulled the commit in. I had to update a few things though, you can see exactly what in 88852eeba545dd07aadb638b99a6c7a06c106cd2 and  46dee4de102dadf70ac781781e66fa7bba3624c3.

All three things you mention there are reasons I don't like MSTest. On the [TestFixture] in the deep base class, that comes from using http://nuget.org/packages/TinySpec.NUnit/, which is a lightweight implementation of a BDD framework on top of NUnit.

As for your last question, I just don't know. I'm sure that spinning up a test repo through the API in an integration test would be perfectly possible. Then you have to make sure that the repo is deleted and recreated before each test run.

Alternatively a static repo could be created and just used for testing various things, but then you still have the same problem of making sure that anything which is created as part of the integration tests is cleaned up.

Either way, you'd also have to consider the case where developers are executing the tests concurrently (unlikely at this time, but you never know). It'd be an epic shit storm.

On top of all that, for the tests to be a proper integration test, I think that there'd have to be an automated way of verifying that stuff on github.com had updated by scraping the html. Ewww.

To be honest, I'm edging away from the idea that integration tests are the best way to test the API. I'm just thinking whether writing a full client (e.g. something actually better than https://github.com/sgrassie/GithubClient) which uses the API is a better way to test it, and to just go with manually verifying that changes which are made in the client are accurately reflected on github and vice-versa.

Of course, all this talk is fine and dandy, and I'm happy to continue, but, I've just got a feeling that it will all be rendered obsolete when github get round to extracting a .NET lib from GitHub for Windows for http://octokit.github.io/.

**Comment by drdamour** [comment]
concurrent collisions could be avoided by creating a new repo for each test run.  That tinyspec was kinda cool, and this was my first exposure to BDD.  As a programmer i didn't see much value, although i did like that fluent assertations library quite a bit!

I didn't understand what should go in context and what should go in because.

Why scrape the HTML & not just use the retrieval APIs to validate the state changed as expected?

octokit adding .net support would render this mostly useless, i didn't even know about octokit.

**Pull request merged**
